FROM node:24-alpine3.22

# Install dependencies
RUN apk update && apk add --no-cache \
    git \
    bash \
    curl \
    python3 \
    make \
    g++

RUN npm install -g pnpm@latest-10

# Create working directory
WORKDIR /workspaces

# Default command
CMD ["bash"]
